name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t heatmap-api:latest .

      - name: Run container in background
        run: |
          docker run -d -p 8000:8000 --name heatmap-api heatmap-api:latest
          sleep 5

      - name: Test FastAPI /docs
        run: |
          curl --fail http://localhost:8000/docs

      - name: Test /generate?object_filter=person
        run: |
          curl --fail -o output.png "http://localhost:8000/generate?object_filter=person"
          test -s output.png 

      - name: Stop and clean container
        if: always()
        run: |
          docker stop heatmap-api
          docker rm heatmap-api
